# Generated by Django 6.0 on 2026-02-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0010_section_classroom_attendancesession_rollingqrtoken_and_more'),
        ('student_app', '0002_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='faculty_app.section'),
        ),
    ]
