# Generated by Django 6.0 on 2026-01-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0002_masterfaculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterfaculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculty Master'},
        ),
    ]
