# Generated by Django 6.0 on 2026-01-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0004_alter_masterfaculty_enrollment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfaculty',
            name='enrollment_id',
            field=models.IntegerField(unique=True),
        ),
    ]
