# Generated by Django 6.0 on 2026-01-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0006_alter_masterfaculty_enrollment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
