# Generated by Django 6.0 on 2026-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0007_teacher_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
